-- Add the "Basic AI" choice to the per-account AI mode.
--
-- The product offers exactly three modes and a customer must be able to pick one
-- explicitly:
--   BASIC_AI  - Acme Jobs pays the provider bill, included in a paid plan
--   MANUAL    - no AI at all, free
--   BYOK      - the customer supplies their own provider key and pays them
--
-- Previously a provider name such as GEMINI was ambiguous: it did not say whether
-- the account was using Acme's key or its own. Without this value a customer who
-- added a key could not switch back to Basic AI without deleting their key.

ALTER TYPE "AIProviderName" ADD VALUE 'ACME_BASIC';

-- A new enum value cannot be used in the same transaction that adds it on older
-- PostgreSQL. This migration therefore only adds the value; Prisma Client is
-- regenerated by `prisma generate`, which reads the schema, not the database.