import { test, expect, type Page } from "@playwright/test";
import { AI_BASE_URL } from "../playwright.config";

/**
 * The three AI-first journeys, end to end, on the FREE plan, against a server
 * whose AI and job feed are local mocks (e2e/mock-services.ts). What is under
 * test is the real app: one primary button, a result labelled with the AI that
 * produced it, no upsell, and Manual Mode only as a secondary option.
 */
test.use({ baseURL: AI_BASE_URL });
test.describe.configure({ mode: "serial" });

const PASSWORD = "acme-demo-password-2026";

async function signInFree(page: Page) {
  await page.goto("/login");
  await page.getByLabel("Email").fill("free@acmejobs.local");
  await page.getByLabel("Password").fill(PASSWORD);
  await page.getByRole("button", { name: /Sign in/i }).click();
  await page.waitForURL(/\/app/, { timeout: 45_000 });
}

test("tailor: paste a job, one click, review changes, save, download", async ({
  page,
}) => {
  test.setTimeout(240_000);
  await signInFree(page);
  await page.goto("/app/tailor");

  // No paid-only gate and no mode picker: three steps and one button.
  await expect(page.getByText(/Complete Edition feature/i)).toHaveCount(0);
  await page.getByRole("tab", { name: "Paste text" }).click();
  await page
    .getByLabel("Job description")
    .fill(
      `Product Designer ${Date.now()}. You will own product design end to end, ` +
        "build prototypes in Figma, contribute to our design system and work " +
        "closely with engineering. Experience with user research is required.",
    );
  await page.getByLabel("Job title (optional)").fill("Product Designer");
  await page.getByRole("button", { name: "Tailor my resume" }).click();

  await expect(page.getByTestId("generated-by")).toContainText(
    "Generated by OpenAI",
    { timeout: 90_000 },
  );
  await expect(page.getByText("What changed and why")).toBeVisible();
  await expect(page.getByText("Keyword match")).toBeVisible();
  // An unknown skill is asked about, not added.
  await expect(page.getByText(/Kubernetes\. Have you used it/)).toBeVisible();

  const changes = page.getByTestId("tailor-change");
  await expect(changes.first()).toBeVisible();
  // Highlighted diff of the AI edit.
  await expect(changes.first().locator("ins").first()).toBeVisible();
  // One-click reject, then accept again.
  await changes.first().getByRole("button", { name: "Reject" }).click();
  await changes.first().getByRole("button", { name: "Accept" }).click();

  await page.getByRole("button", { name: "Save tailored resume" }).click();
  await expect(page.getByText("Saved as a new version")).toBeVisible({
    timeout: 60_000,
  });
  const pdf = page.getByRole("link", { name: "Download PDF" });
  await expect(pdf).toHaveAttribute("href", /\/api\/resumes\/.+\/pdf$/);
  const res = await page.request.get((await pdf.getAttribute("href"))!);
  expect(res.status()).toBe(200);
  expect(res.headers()["content-type"]).toContain("pdf");
});

test("job search: AI-planned queries, provider health, 50 results, load more, no upsell", async ({
  page,
}) => {
  test.setTimeout(240_000);
  await signInFree(page);
  await page.goto("/app/jobs?mt=Product+Designer&mw=REMOTE&refresh=1");

  await expect(page.getByTestId("provider-health")).toContainText(
    /Remotive ✓ \d+/,
    { timeout: 120_000 },
  );
  await expect(page.getByText(/Queries planned by OpenAI/)).toBeVisible();
  await expect(page.getByText(/ranked by OpenAI/)).toBeVisible();

  const results = page.getByTestId("job-results").locator("> li");
  await expect(results).toHaveCount(50);
  await expect(page.getByText("Why this fits:").first()).toBeVisible();
  await expect(page.getByText(/Source: Remotive/).first()).toBeVisible();

  await page.getByRole("link", { name: /Load more/ }).click();
  await expect(results).toHaveCount(60, { timeout: 60_000 });

  // No "Unlock N more" anywhere; LinkedIn etc. are prefilled links, not scraped.
  await expect(page.getByText(/Unlock \d+ more/i)).toHaveCount(0);
  await expect(page.getByRole("link", { name: /LinkedIn/ })).toHaveAttribute(
    "href",
    /linkedin\.com\/jobs\/search\/\?keywords=Product\+Designer/,
  );
});

test("mock interview: pick, Quick, answer, coached feedback, summary", async ({
  page,
}) => {
  test.setTimeout(240_000);
  await signInFree(page);
  await page.goto("/app/interviews/practice");

  await expect(page.getByText(/Questions allowed/i)).toHaveCount(0);
  await page.getByLabel("Job").selectOption({ value: "" });
  await page.getByLabel("Target role").fill("Product Designer");
  await page.getByLabel(/Quick/).check();
  await page.getByRole("button", { name: "Start" }).click();

  await expect(page.getByText(/Question 1 of 5/)).toBeVisible({
    timeout: 90_000,
  });
  await expect(page.getByText(/Questions by OpenAI/)).toBeVisible();
  await page
    .getByLabel(/Your answer/i)
    .fill(
      "I ran user interviews, found the checkout flow confused people, and redesigned it with engineering.",
    );
  await page.getByRole("button", { name: "Submit answer" }).click();

  const feedback = page.getByTestId("interview-feedback");
  await expect(feedback).toBeVisible({ timeout: 90_000 });
  await expect(feedback).toContainText("One improvement");
  await expect(feedback).toContainText("A stronger answer");
  await expect(feedback.getByRole("meter")).toHaveCount(4);

  await page
    .getByRole("button", { name: "End interview and see summary" })
    .click();
  const summary = page.getByTestId("interview-summary");
  await expect(summary).toBeVisible({ timeout: 60_000 });
  await expect(summary).toContainText("Top strengths");
  await expect(summary).toContainText("Top fixes");
});
