import type { Metadata, Viewport } from "next";
import "./globals.css";
// Self-hosted Inter Variable (SIL OFL). Replaces the Clash Display / Satoshi
// pair that was loaded from a third-party CDN at one weight each, which is why
// headings fell back to Arial Black and 600/700 weights were synthesised.
import "@fontsource-variable/inter";
import { ServiceWorkerRegistration } from "@/components/service-worker-registration";

export const metadata: Metadata = {
  title: {
    default: "Acme Jobs — Better Opportunities Ahead",
    template: "%s | Acme Jobs",
  },
  description:
    "Acme Jobs gives you practical AI-powered systems to understand job descriptions, improve your resume, prepare for interviews, and turn your real experience into stronger applications.",
  applicationName: "Acme Jobs",
  // Generated by the typed manifest route so the values cannot drift from the
  // install metadata browsers and Windows read.
  manifest: "/manifest.webmanifest",
  // The vector mark for modern browsers, the raster for Windows and older
  // Safari. Previously only a zero-byte icon.svg was declared, so the tab showed
  // no logo at all.
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
  },
  appleWebApp: {
    capable: true,
    title: "Acme Jobs",
    statusBarStyle: "black-translucent",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Matches the navy in the mark rather than the old grey.
  themeColor: "#faf6ee",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          // Applies the saved theme before first paint to avoid a flash.
          dangerouslySetInnerHTML={{
            __html: `(function(){try{if(localStorage.getItem('acme-design')!=='warm-editorial-v1'){localStorage.setItem('acme-theme','light');localStorage.setItem('acme-design','warm-editorial-v1');}var t=localStorage.getItem('acme-theme')||'light';var d=t==='dark'||(t==='system'&&window.matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.classList.toggle('dark',d);}catch(e){}})();`,
          }}
        />
      </head>
      <body>
        <a className="skip-link" href="#main">
          Skip to main content
        </a>
        {children}
        <ServiceWorkerRegistration />
      </body>
    </html>
  );
}
