import { requireUser } from "@/lib/auth";
import { getResume, RESUME_CONTENT_SCHEMA } from "@/services/resume-service";
import { buildPdf, pdfResponse } from "@/lib/export";
import { asAppError, userFacingMessage } from "@/lib/errors";
import { env } from "@/lib/env";

export const dynamic = "force-dynamic";

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ resumeId: string }> },
) {
  try {
    const user = await requireUser();
    const { resumeId } = await params;
    const resume = await getResume(user.id, resumeId);
    const content = RESUME_CONTENT_SCHEMA.parse(
      resume.versions[0]?.content ?? {},
    );

    const sections = [
      content.summary ? { heading: "Summary", lines: [content.summary] } : null,
      content.skills.length
        ? { heading: "Skills", lines: content.skills.map((s) => `• ${s}`) }
        : null,
      content.experiences.length
        ? {
            heading: "Experience",
            lines: content.experiences.flatMap((e) => [
              `${e.title} — ${e.company}${e.location ? `, ${e.location}` : ""}`,
              `${e.startDate}${e.endDate ? ` – ${e.endDate}` : ""}`,
              ...e.bullets.map((b) => `• ${b}`),
              "",
            ]),
          }
        : null,
      content.projects.length
        ? {
            heading: "Projects",
            lines: content.projects.flatMap((p) => [
              `${p.name}${p.role ? ` — ${p.role}` : ""}`,
              ...(p.tech.length ? [p.tech.join(", ")] : []),
              ...p.bullets.map((b) => `• ${b}`),
              "",
            ]),
          }
        : null,
      content.education.length
        ? {
            heading: "Education",
            lines: content.education.map((e) =>
              [e.degree, e.field, e.institution].filter(Boolean).join(" — "),
            ),
          }
        : null,
      content.certifications.length
        ? {
            heading: "Certifications",
            lines: content.certifications.map(
              (c) => `• ${c.name}${c.issuer ? ` — ${c.issuer}` : ""}`,
            ),
          }
        : null,
    ].filter(Boolean) as Array<{ heading: string; lines: string[] }>;

    const buffer = await buildPdf({
      title: content.contact.fullName || resume.label,
      subtitle: resume.label,
      contact: [
        content.contact.email,
        content.contact.phone,
        content.contact.location,
        content.contact.linkedinUrl,
      ].filter(Boolean),
      sections,
      footer: `Generated by Acme Jobs v${env().APP_VERSION} · Your experience. AI-assisted. Never invented.`,
    });

    return pdfResponse(
      `${resume.label.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.pdf`,
      buffer,
    );
  } catch (e) {
    const err = asAppError(e);
    return new Response(userFacingMessage(err), { status: err.status });
  }
}
