import { prisma } from "@/lib/db";
import { Errors } from "@/lib/errors";
import { storageProvider } from "@/lib/storage";
import { buildPdf } from "@/lib/export";
import { toCsv } from "@/lib/utils";
import {
  RESUME_CONTENT_SCHEMA,
  flattenResumeText,
} from "@/services/resume-service";
import type { ClaimedJob } from "@/queue/queue";

export async function handleExportPdf(
  job: ClaimedJob,
): Promise<{ fileName: string; sizeBytes: number }> {
  const { userId, kind, documentId } = job.payload as {
    userId: string;
    kind: string;
    documentId?: string;
  };
  if (!userId) throw Errors.validation("Export job is missing a user id.");

  const owner = await prisma.user.findUnique({
    where: { id: userId },
    select: { id: true },
  });
  if (!owner)
    throw Errors.validation("Export owner no longer exists.", undefined);

  const spec = await buildExportSpec(userId, kind, documentId);
  const buffer = buildPdf(spec);
  const stored = await storageProvider().put({
    scope: "exports",
    ownerId: userId,
    buffer,
    mimeType: "application/pdf",
    originalName: `${kind}.pdf`,
  });

  await prisma.dataExportRequest.create({
    data: {
      userId,
      kind,
      format: "pdf",
      status: "SUCCEEDED",
      fileName: stored.originalName,
      storagePath: stored.path,
      sizeBytes: stored.size,
      workItemId: job.id,
      completedAt: new Date(),
    },
  });

  return { fileName: stored.originalName, sizeBytes: stored.size };
}

export async function handleExportCsv(
  job: ClaimedJob,
): Promise<{ rows: number }> {
  const { userId, dataset } = job.payload as {
    userId: string;
    dataset: string;
  };
  if (!userId) throw Errors.validation("Export job is missing a user id.");

  const rows =
    dataset === "evidence"
      ? await prisma.evidence.findMany({
          where: { userId },
          select: {
            statement: true,
            claimType: true,
            verificationStatus: true,
            metricValue: true,
            metricUnit: true,
            sourceDescription: true,
          },
        })
      : dataset === "applications"
        ? await prisma.application.findMany({
            where: { userId },
            select: {
              status: true,
              appliedAt: true,
              nextAction: true,
              fitClassification: true,
            },
          })
        : [];

  const csv = toCsv(rows as unknown as Array<Record<string, unknown>>);
  await storageProvider().put({
    scope: "exports",
    ownerId: userId,
    buffer: Buffer.from(csv, "utf8"),
    mimeType: "text/csv",
    originalName: `${dataset}.csv`,
  });

  await prisma.dataExportRequest.create({
    data: {
      userId,
      kind: dataset,
      format: "csv",
      status: "SUCCEEDED",
      workItemId: job.id,
      completedAt: new Date(),
    },
  });

  return { rows: rows.length };
}

async function buildExportSpec(
  userId: string,
  kind: string,
  documentId?: string,
) {
  const footer =
    "Generated by Acme Jobs · Your experience. AI-assisted. Never invented.";

  if (kind === "career") {
    const [profile, career, employments, education, skills] = await Promise.all(
      [
        prisma.userProfile.findUnique({ where: { userId } }),
        prisma.careerMasterProfile.findUnique({ where: { userId } }),
        prisma.employmentRecord.findMany({
          where: { userId },
          orderBy: { startDate: "desc" },
        }),
        prisma.educationRecord.findMany({ where: { userId } }),
        prisma.skill.findMany({ where: { userId } }),
      ],
    );
    return {
      title:
        [profile?.firstName, profile?.lastName].filter(Boolean).join(" ") ||
        "Career profile",
      subtitle: career?.targetRolePrimary
        ? `Targeting ${career.targetRolePrimary}`
        : "Career profile export",
      contact: [profile?.email, profile?.phone, profile?.locationCity].filter(
        Boolean,
      ) as string[],
      sections: [
        career?.professionalSummary
          ? { heading: "Summary", lines: [career.professionalSummary] }
          : { heading: "Summary", lines: ["(not provided)"] },
        { heading: "Skills", lines: skills.map((s) => `• ${s.name}`) },
        {
          heading: "Experience",
          lines: employments.flatMap((e) => [
            `${e.jobTitle} — ${e.companyName}`,
            ...e.highlights.map((h) => `• ${h}`),
            "",
          ]),
        },
        {
          heading: "Education",
          lines: education.map((e) =>
            [e.degree, e.fieldOfStudy, e.institution]
              .filter(Boolean)
              .join(" — "),
          ),
        },
      ],
      footer,
    };
  }

  if (kind === "interview-brief" && documentId) {
    const { interviewCommandCenter } =
      await import("@/services/interview-service");
    const data = await interviewCommandCenter(userId, documentId);
    return {
      title: `${data.interview.company} interview brief`,
      subtitle: `${data.interview.role} · ${data.interview.stage.toLowerCase()}`,
      sections: [
        {
          heading: "Requirements",
          lines: data.jobRequirements.map(
            (r) =>
              `• [${r.strength}] ${r.text}${r.isMustHave ? " (required)" : ""}`,
          ),
        },
        {
          heading: "Strongest evidence",
          lines: data.strongestEvidence.map((e) => `• ${e.statement}`),
        },
        {
          heading: "Questions to ask",
          lines: data.questionsToAsk.map((q) => `• ${q}`),
        },
        {
          heading: "Risks and gaps",
          lines: [...data.risks, ...data.gaps].map((r) => `• ${r}`),
        },
        {
          heading: "Checklist",
          lines: data.checklist.map((c) => `• ${c.label}`),
        },
      ],
      footer,
    };
  }

  // resume
  const resume = documentId
    ? await prisma.resume.findFirst({
        where: { id: documentId, userId },
        include: { versions: { orderBy: { version: "desc" }, take: 1 } },
      })
    : await prisma.resume.findFirst({
        where: { userId, isMaster: true },
        include: { versions: { orderBy: { version: "desc" }, take: 1 } },
      });
  if (!resume) throw Errors.notFound("Resume");

  const content = RESUME_CONTENT_SCHEMA.parse(
    resume.versions[0]?.content ?? {},
  );
  return {
    title: content.contact.fullName || resume.label,
    subtitle: resume.label,
    contact: [
      content.contact.email,
      content.contact.phone,
      content.contact.location,
    ].filter(Boolean) as string[],
    sections: [
      { heading: "Summary", lines: [flattenResumeText(content)] },
      { heading: "Skills", lines: content.skills.map((s) => `• ${s}`) },
      {
        heading: "Experience",
        lines: content.experiences.flatMap((e) => [
          `${e.title} — ${e.company}`,
          ...e.bullets.map((b) => `• ${b}`),
          "",
        ]),
      },
    ],
    footer,
  };
}
